import { CategoryNodeTag } from "@/models/admin/category";

export const PLASTIC_SURGERY_CATEGORIES: CategoryNodeTag[] = [
{
  id: "P1C",
  key: "eye",
  ko: "눈",
  en: "Eye",
  children: [
    {
      id: "P2CB",
      key: "double_eyelid",
      ko: "쌍꺼풀",
      en: "Double Eyelid",
      children: [
        {
          id: "P3CBC",
          key: "natural_adhesion",
          ko: "자연유착",
          en: "Natural Adhesion",
        },
        {
          id: "P3CBA",
          key: "buried",
          ko: "매몰",
          en: "Buried",
        },
        {
          id: "P3CBB",
          key: "incision",
          ko: "절개",
          en: "Incision",
        },
        {
          id: "P3CBD",
          key: "partial_incision",
          ko: "부분벌개",
          en: "Partial Incision",
        },
      ],
    },
    {
      id: "P2CA",
      key: "canthoplasty",
      ko: "트임",
      en: "Canthoplasty",
      children: [
        {
          id: "P3CAB",
          key: "epicanthoplasty",
          ko: "앞트임",
          en: "Epicanthoplasty",
        },
        {
          id: "P3CAC",
          key: "lateral_canthoplasty",
          ko: "뒤트임",
          en: "Lateral Canthoplasty",
        },
        {
          id: "P3CAF",
          key: "upper_canthoplasty",
          ko: "윗트임",
          en: "Upper Canthoplasty",
        },
        {
          id: "P3CAD",
          key: "lower_canthoplasty",
          ko: "밑트임",
          en: "Lower Canthoplasty",
        },
        {
          id: "P3CAE",
          key: "mongolian_fold",
          ko: "몽고트임",
          en: "Mongolian Fold",
        },
        {
          id: "P3CAA",
          key: "canthoplasty_revision",
          ko: "트임복원",
          en: "Canthoplasty Revision",
        },
      ],
    },
    {
      id: "P2CE",
      key: "ptosis_correction",
      ko: "눈매교정",
      en: "Ptosis Correction",
      children: [
        {
          id: "P3CEA",
          key: "incision",
          ko: "절개",
          en: "Incision",
        },
        {
          id: "P3CEB",
          key: "non_incision",
          ko: "비절개",
          en: "Non Incision",
        },
      ],
    },
    {
      id: "P2CD",
      key: "eye_shape_correction",
      ko: "눈모양교정",
      en: "Eye Shape Correction",
      children: [
        {
          id: "P3CDE",
          key: "lower_eyelid_fat_reposition",
          ko: "눈밑지방재배치",
          en: "Lower Eyelid Fat Reposition",
        },
        {
          id: "P3CDF",
          key: "upper_blepharoplasty",
          ko: "상안검",
          en: "Upper Blepharoplasty",
        },
        {
          id: "P3CDC",
          key: "lower_blepharoplasty",
          ko: "하안검",
          en: "Lower Blepharoplasty",
        },
        {
          id: "P3CDA",
          key: "brow_lift",
          ko: "눈썹거상",
          en: "Brow Lift",
        },
        {
          id: "P3CDD",
          key: "lower_eyelid_fat_removal",
          ko: "눈밑지방제거",
          en: "Lower Eyelid Fat Removal",
        },
        {
          id: "P3CDB",
          key: "eyelid_fat_removal",
          ko: "눈꺼풀지방제거",
          en: "Eyelid Fat Removal",
        },
      ],
    },
    {
      id: "P2CC",
      key: "eye_revision",
      ko: "눈재수술",
      en: "Eye Revision",
      children: [
        {
          id: "P3CCB",
          key: "double_eyelid",
          ko: "쌍꺼풀",
          en: "Double Eyelid",
        },
        {
          id: "P3CCA",
          key: "canthoplasty",
          ko: "트임",
          en: "Canthoplasty",
        },
        {
          id: "P3CCD",
          key: "ptosis_correction",
          ko: "눈매교정",
          en: "Ptosis Correction",
        },
        {
          id: "P3CCC",
          key: "eye_shape_correction",
          ko: "눈모양교정",
          en: "Eye Shape Correction",
        },
      ],
    },
  ],
},
{
  id: "P1F",
  key: "nose",
  ko: "코",
  en: "Nose",
  children: [
    {
      id: "P2FB",
      key: "bridge",
      ko: "콧대",
      en: "Bridge",
      children: [
        {
          id: "P3FBA",
          key: "bridge_autologous",
          ko: "콧대(자가조직)",
          en: "Bridge Autologous",
        },
        {
          id: "P3FBB",
          key: "bridge_implant",
          ko: "콧대(보형물)",
          en: "Bridge Implant",
        },
        {
          id: "P3FBC",
          key: "osteotomy",
          ko: "코절골술",
          en: "Osteotomy",
        },
      ],
    },
    {
      id: "P2FE",
      key: "tip",
      ko: "코끝",
      en: "Tip",
      children: [
        {
          id: "P3FEA",
          key: "tip_autologous",
          ko: "코끝(자가조직)",
          en: "Tip Autologous",
        },
        {
          id: "P3FEB",
          key: "tip_implant",
          ko: "코끝(보형물)",
          en: "Tip Implant",
        },
        {
          id: "P3FEC",
          key: "tip_lengthening",
          ko: "코길이연장",
          en: "Tip Lengthening",
        },
      ],
    },
    {
      id: "P2FA",
      key: "ala",
      ko: "콧볼",
      en: "Ala",
      children: [
        {
          id: "P3FAB",
          key: "non_incision",
          ko: "비절개",
          en: "Non Incision",
        },
        {
          id: "P3FAA",
          key: "medial_incision",
          ko: "내측절개",
          en: "Medial Incision",
        },
      ],
    },
    {
      id: "P2FC",
      key: "functional",
      ko: "기능코",
      en: "Functional",
      children: [
        {
          id: "P3FCB",
          key: "rhinitis_sinusitis",
          ko: "비염/축농증",
          en: "Rhinitis Sinusitis",
        },
        {
          id: "P3FCA",
          key: "nasal_valve_stenosis",
          ko: "비밸브협착",
          en: "Nasal Valve Stenosis",
        },
        {
          id: "P3FCC",
          key: "septal_deviation",
          ko: "비중격만곡",
          en: "Septal Deviation",
        },
      ],
    },
    {
      id: "P2FD",
      key: "nose_revision",
      ko: "코재수술",
      en: "Nose Revision",
      children: [
        {
          id: "P3FDB",
          key: "bridge",
          ko: "콧대",
          en: "Bridge",
        },
        {
          id: "P3FDD",
          key: "tip",
          ko: "코끝",
          en: "Tip",
        },
        {
          id: "P3FDA",
          key: "ala",
          ko: "콧볼",
          en: "Ala",
        },
        {
          id: "P3FDC",
          key: "functional",
          ko: "기능코",
          en: "Functional",
        },
      ],
    },
  ],
},
{
  id: "P1D",
  key: "fat",
  ko: "지방흡입/이식",
  en: "Fat Graft",
  children: [
    {
      id: "P2DB",
      key: "body_liposuction",
      ko: "바디지방흡입",
      en: "Body Liposuction",
      children: [
        {
          id: "P3DBA",
          key: "abdomen",
          ko: "복부",
          en: "Abdomen",
        },
        {
          id: "P3DBB",
          key: "arm",
          ko: "팔",
          en: "Arm",
        },
        {
          id: "P3DBH",
          key: "thigh",
          ko: "허벅지",
          en: "Thigh",
        },
        {
          id: "P3DBG",
          key: "knee_calf_ankle",
          ko: "무릎/종아리/발목",
          en: "Knee Calf Ankle",
        },
        {
          id: "P3DBE",
          key: "buttock",
          ko: "엉덩이",
          en: "Buttock",
        },
        {
          id: "P3DBI",
          key: "trapezius_collar_back",
          ko: "승모근/쇄골/등",
          en: "Trapezius Collar Back",
        },
        {
          id: "P3DBF",
          key: "flank_love_handle",
          ko: "옆구리/러브핸들",
          en: "Flank Love Handle",
        },
        {
          id: "P3DBD",
          key: "breast",
          ko: "가슴",
          en: "Breast",
        },
        {
          id: "P3DBC",
          key: "armpit_accessory_breast",
          ko: "겨드랑이/부유방",
          en: "Armpit Accessory Breast",
        },
        {
          id: "P3DBJ",
          key: "whole_body",
          ko: "전신",
          en: "Whole Body",
        },
      ],
    },
    {
      id: "P2DD",
      key: "face_liposuction",
      ko: "얼굴지방흡입",
      en: "Face Liposuction",
      children: [
        {
          id: "P3DDD",
          key: "full_face",
          ko: "풀페이스",
          en: "Full Face",
        },
        {
          id: "P3DDC",
          key: "forehead_glabella",
          ko: "이마/미간",
          en: "Forehead Glabella",
        },
        {
          id: "P3DDA",
          key: "cheek_zygomatic",
          ko: "볼/광대",
          en: "Cheek Zygomatic",
        },
        {
          id: "P3DDB",
          key: "chin",
          ko: "턱",
          en: "Chin",
        },
        {
          id: "P3DDE",
          key: "nasolabial_fold",
          ko: "팔자",
          en: "Nasolabial Fold",
        },
      ],
    },
    {
      id: "P2DC",
      key: "face_fat_graft",
      ko: "얼굴지방이식",
      en: "Face Fat Graft",
      children: [
        {
          id: "P3DCE",
          key: "full_face",
          ko: "풀페이스",
          en: "Full Face",
        },
        {
          id: "P3DCD",
          key: "forehead_glabella",
          ko: "이마/미간",
          en: "Forehead Glabella",
        },
        {
          id: "P3DCA",
          key: "cheek_zygomatic",
          ko: "볼/광대",
          en: "Cheek Zygomatic",
        },
        {
          id: "P3DCC",
          key: "eyes",
          ko: "눈",
          en: "Eyes",
        },
        {
          id: "P3DCB",
          key: "chin",
          ko: "턱",
          en: "Chin",
        },
        {
          id: "P3DCH",
          key: "temple",
          ko: "관자놀이",
          en: "Temple",
        },
        {
          id: "P3DCG",
          key: "nasolabial_fold",
          ko: "팔자",
          en: "Nasolabial Fold",
        },
        {
          id: "P3DCF",
          key: "lips",
          ko: "입술",
          en: "Lips",
        },
      ],
    },
    {
      id: "P2DA",
      key: "body_fat_graft",
      ko: "바디지방이식",
      en: "Body Fat Graft",
      children: [
        {
          id: "P3DAA",
          key: "breast",
          ko: "가슴",
          en: "Breast",
        },
        {
          id: "P3DAB",
          key: "buttock_pelvis",
          ko: "엉덩이/골반",
          en: "Buttock Pelvis",
        },
        {
          id: "P3DAC",
          key: "calf",
          ko: "종아리",
          en: "Calf",
        },
      ],
    },
  ],
},
{
  id: "P1G",
  key: "outline",
  ko: "안면윤곽/양악",
  en: "Facial Contour/Jaw",
  children: [
    {
      id: "P2GE",
      key: "zygoma",
      ko: "광대",
      en: "Zygoma",
      children: [
        {
          id: "P3GEA",
          key: "zygoma_implant",
          ko: "광대확대(보형물)",
          en: "Zygoma Implant",
        },
        {
          id: "P3GEB",
          key: "zygoma_reduction",
          ko: "광대축소",
          en: "Zygoma Reduction",
        },
      ],
    },
    {
      id: "P2GA",
      key: "contour",
      ko: "윤곽",
      en: "Contour",
      children: [
        {
          id: "P3GAE",
          key: "square_jaw",
          ko: "사각턱",
          en: "Square Jaw",
        },
        {
          id: "P3GAA",
          key: "chin",
          ko: "턱끝",
          en: "Chin",
        },
        {
          id: "P3GAC",
          key: "double_chin",
          ko: "이중턱",
          en: "Double Chin",
        },
        {
          id: "P3GAB",
          key: "complex_face_vline",
          ko: "복합안면/V라인",
          en: "Complex Face Vline",
        },
        {
          id: "P3GAD",
          key: "facelift",
          ko: "안면거상",
          en: "Facelift",
        },
      ],
    },
    {
      id: "P2GC",
      key: "forehead",
      ko: "이마",
      en: "Forehead",
      children: [
        {
          id: "P3GCA",
          key: "forehead_implant",
          ko: "이마확대(보형물)",
          en: "Forehead Implant",
        },
        {
          id: "P3GCC",
          key: "forehead_reduction",
          ko: "이마축소",
          en: "Forehead Reduction",
        },
        {
          id: "P3GCB",
          key: "forehead_lift",
          ko: "이마거상",
          en: "Forehead Lift",
        },
      ],
    },
    {
      id: "P2GD",
      key: "two_jaw",
      ko: "양악",
      en: "Two Jaw",
      children: [
        {
          id: "P3GDB",
          key: "two_jaw",
          ko: "양악",
          en: "Two Jaw",
        },
        {
          id: "P3GDC",
          key: "upper_jaw",
          ko: "상악",
          en: "Upper Jaw",
        },
        {
          id: "P3GDA",
          key: "lower_jaw",
          ko: "하악",
          en: "Lower Jaw",
        },
      ],
    },
    {
      id: "P2GB",
      key: "contour_revision",
      ko: "안면윤곽재수술",
      en: "Facial Contour Revision",
      children: [
        {
          id: "P3GBD",
          key: "zygoma",
          ko: "광대",
          en: "Zygoma",
        },
        {
          id: "P3GBA",
          key: "contour",
          ko: "윤곽",
          en: "Contour",
        },
        {
          id: "P3GBB",
          key: "forehead",
          ko: "이마",
          en: "Forehead",
        },
        {
          id: "P3GBC",
          key: "two_jaw",
          ko: "양악",
          en: "Two Jaw",
        },
      ],
    },
  ],
},
{
  id: "P1A",
  key: "breast",
  ko: "가슴",
  en: "Breast",
  children: [
    {
      id: "P2AB",
      key: "breast_shape_correction",
      ko: "가슴모양교정",
      en: "Breast Shape Correction",
      children: [
        {
          id: "P3ABA",
          key: "augmentation_implant",
          ko: "가슴확대(보형물)",
          en: "Augmentation Implant",
        },
        {
          id: "P3ABE",
          key: "mastopexy",
          ko: "가슴거상",
          en: "Mastopexy",
        },
        {
          id: "P3ABF",
          key: "reduction",
          ko: "가슴축소",
          en: "Reduction",
        },
        {
          id: "P3ABD",
          key: "implant_removal",
          ko: "가슴보형물제거",
          en: "Implant Removal",
        },
        {
          id: "P3ABC",
          key: "foreign_body_removal",
          ko: "가슴이물질제거",
          en: "Foreign Body Removal",
        },
        {
          id: "P3ABB",
          key: "axillary_fat_removal",
          ko: "부유방지방제거",
          en: "Axillary Fat Removal",
        },
      ],
    },
    {
      id: "P2AC",
      key: "nipple_areola",
      ko: "유두/유륜",
      en: "Nipple Areola",
      children: [
        {
          id: "P3ACA",
          key: "inverted_nipple",
          ko: "함몰유두",
          en: "Inverted Nipple",
        },
        {
          id: "P3ACB",
          key: "nipple_areola_reduction",
          ko: "유두/유륜축소",
          en: "Nipple Areola Reduction",
        },
      ],
    },
    {
      id: "P2AA",
      key: "breast_revision",
      ko: "가슴재수술",
      en: "Breast Revision",
      children: [
        {
          id: "P3AAA",
          key: "breast_shape_correction",
          ko: "가슴모양교정",
          en: "Breast Shape Correction",
        },
        {
          id: "P3AAB",
          key: "nipple_areola",
          ko: "유두/유륜",
          en: "Nipple Areola",
        },
      ],
    },
  ],
},
{
  id: "P1E",
  key: "mens",
  ko: "남자성형",
  en: "Mens",
  children: [
    {
      id: "P2EB",
      key: "eye",
      ko: "눈",
      en: "Eye",
      children: [
        {
          id: "P3EBB",
          key: "double_eyelid_or_no_eyelid",
          ko: "쌍꺼풀/무쌍",
          en: "Double Eyelid Or No Eyelid",
        },
        {
          id: "P3EBA",
          key: "canthoplasty",
          ko: "트임",
          en: "Canthoplasty",
        },
        {
          id: "P3EBD",
          key: "ptosis_correction",
          ko: "눈매교정",
          en: "Ptosis Correction",
        },
        {
          id: "P3EBC",
          key: "eye_shape_correction",
          ko: "눈모양교정",
          en: "Eye Shape Correction",
        },
      ],
    },
    {
      id: "P2EE",
      key: "nose",
      ko: "코",
      en: "Nose",
      children: [
        {
          id: "P3EEB",
          key: "bridge",
          ko: "콧대",
          en: "Bridge",
        },
        {
          id: "P3EED",
          key: "tip",
          ko: "코끝",
          en: "Tip",
        },
        {
          id: "P3EEA",
          key: "ala",
          ko: "콧볼",
          en: "Ala",
        },
        {
          id: "P3EEC",
          key: "functional",
          ko: "기능코",
          en: "Functional",
        },
      ],
    },
    {
      id: "P2EA",
      key: "breast",
      ko: "가슴",
      en: "Breast",
      children: [
        {
          id: "P3EAA",
          key: "gynecomastia",
          ko: "여유증",
          en: "Gynecomastia",
        },
        {
          id: "P3EAB",
          key: "nipple_areola",
          ko: "유두/유륜",
          en: "Nipple Areola",
        },
      ],
    },
    {
      id: "P2ED",
      key: "liposuction_fat_graft",
      ko: "지방흡입/이식",
      en: "Liposuction/Fat Graft",
      children: [
        {
          id: "P3EDB",
          key: "body_liposuction",
          ko: "바디지방흡입",
          en: "Body Liposuction",
        },
        {
          id: "P3EDD",
          key: "face_liposuction",
          ko: "얼굴지방흡입",
          en: "Face Liposuction",
        },
        {
          id: "P3EDC",
          key: "face_fat_graft",
          ko: "얼굴지방이식",
          en: "Face Fat Graft",
        },
        {
          id: "P3EDA",
          key: "body_fat_graft",
          ko: "바디지방이식",
          en: "Body Fat Graft",
        },
      ],
    },
    {
      id: "P2EC",
      key: "facial_contour_jaw",
      ko: "안면윤곽/양악",
      en: "Facial Contour/Jaw",
      children: [
        {
          id: "P3ECD",
          key: "zygoma",
          ko: "광대",
          en: "Zygoma",
        },
        {
          id: "P3ECA",
          key: "contour",
          ko: "윤곽",
          en: "Contour",
        },
        {
          id: "P3ECB",
          key: "forehead",
          ko: "이마",
          en: "Forehead",
        },
        {
          id: "P3ECC",
          key: "two_jaw",
          ko: "양악",
          en: "Two Jaw",
        },
      ],
    },
  ],
},
{
  id: "P1B",
  key: "etc",
  ko: "기타",
  en: "Etc",
  children: [
    {
      id: "P2BE",
      key: "female_surgery",
      ko: "여성성형",
      en: "Female Surgery",
    },
    {
      id: "P2BA",
      key: "body_lift",
      ko: "바디거상",
      en: "Body Lift",
    },
    {
      id: "P2BF",
      key: "lip_surgery",
      ko: "입술성형",
      en: "Lip Surgery",
    },
    {
      id: "P2BI",
      key: "philtrum_surgery",
      ko: "인중성형",
      en: "Philtrum Surgery",
    },
    {
      id: "P2BG",
      key: "nasolabial_surgery",
      ko: "팔자성형",
      en: "Nasolabial Surgery",
    },
    {
      id: "P2BC",
      key: "dimple_surgery",
      ko: "보조개성형",
      en: "Dimple Surgery",
    },
    {
      id: "P2BB",
      key: "buttock_surgery",
      ko: "엉덩이성형",
      en: "Buttock Surgery",
    },
    {
      id: "P2BD",
      key: "ear_surgery",
      ko: "귀성형",
      en: "Ear Surgery",
    },
    {
      id: "P2BH",
      key: "other_surgery",
      ko: "기타성형",
      en: "Other Surgery",
    },
  ],
},
];
