import { CategoryNodeTag } from "@/models/admin/category";


export const SKIN_BEAUTY_CATEGORIES: CategoryNodeTag[] = [
{
  id: "S1C",
  key: "face",
  ko: "얼굴",
  en: "Face",
  children: [
    {
      id: "S2CC",
      key: "filler",
      ko: "필러",
      en: "Filler",
      children: [
        {
          id: "S3CCF",
          key: "full_face",
          ko: "풀페이스",
          en: "Full Face",
        },
        {
          id: "S3CCE",
          key: "forehead_glabella",
          ko: "이마/미간",
          en: "Forehead Glabella",
        },
        {
          id: "S3CCJ",
          key: "nose",
          ko: "코",
          en: "Nose",
        },
        {
          id: "S3CCG",
          key: "lips_mouth_corner",
          ko: "입술/입꼬리",
          en: "Lips Mouth Corner",
        },
        {
          id: "S3CCC",
          key: "eyes",
          ko: "눈",
          en: "Eyes",
        },
        {
          id: "S3CCB",
          key: "chin",
          ko: "턱",
          en: "Chin",
        },
        {
          id: "S3CCA",
          key: "cheek_zygomatic",
          ko: "볼/광대",
          en: "Cheek Zygomatic",
        },
        {
          id: "S3CCI",
          key: "neck",
          ko: "목",
          en: "Neck",
        },
        {
          id: "S3CCH",
          key: "nasolabial_fold",
          ko: "팔자",
          en: "Nasolabial Fold",
        },
        {
          id: "S3CCL",
          key: "temple",
          ko: "관자놀이",
          en: "Temple",
        },
        {
          id: "S3CCK",
          key: "scalp",
          ko: "두상",
          en: "Scalp",
        },
        {
          id: "S3CCD",
          key: "filler_removal",
          ko: "필러제거",
          en: "Filler Removal",
        },
      ],
    },
    {
      id: "S2CD",
      key: "lifting",
      ko: "리프팅",
      en: "Lifting",
      children: [
        {
          id: "S3CDA",
          key: "laser_lifting",
          ko: "레이저리프팅",
          en: "Laser Lifting",
        },
        {
          id: "S3CDD",
          key: "thread_lifting",
          ko: "실리프팅",
          en: "Thread Lifting",
        },
        {
          id: "S3CDC",
          key: "nose_lifting",
          ko: "코리프팅",
          en: "Nose Lifting",
        },
        {
          id: "S3CDB",
          key: "nerve_block_lifting",
          ko: "신경차단리프팅",
          en: "Nerve Block Lifting",
        },
      ],
    },
    {
      id: "S2CA",
      key: "botox",
      ko: "보톡스",
      en: "Botox",
      children: [
        {
          id: "S3CAE",
          key: "full_face",
          ko: "풀페이스",
          en: "Full Face",
        },
        {
          id: "S3CAB",
          key: "chin",
          ko: "턱",
          en: "Chin",
        },
        {
          id: "S3CAL",
          key: "parotid_gland",
          ko: "침샘",
          en: "Parotid Gland",
        },
        {
          id: "S3CAD",
          key: "forehead_glabella",
          ko: "이마/미간",
          en: "Forehead Glabella",
        },
        {
          id: "S3CAC",
          key: "eyes",
          ko: "눈",
          en: "Eyes",
        },
        {
          id: "S3CAM",
          key: "skin",
          ko: "스킨",
          en: "Skin",
        },
        {
          id: "S3CAH",
          key: "lips_mouth_corner",
          ko: "입술/입꼬리",
          en: "Lips Mouth Corner",
        },
        {
          id: "S3CAF",
          key: "gums",
          ko: "잇몸",
          en: "Gums",
        },
        {
          id: "S3CAG",
          key: "hyperhidrosis",
          ko: "다한증",
          en: "Hyperhidrosis",
        },
        {
          id: "S3CAA",
          key: "cheek_zygomatic",
          ko: "볼/광대",
          en: "Cheek Zygomatic",
        },
        {
          id: "S3CAK",
          key: "nose",
          ko: "코",
          en: "Nose",
        },
        {
          id: "S3CAJ",
          key: "neck",
          ko: "목",
          en: "Neck",
        },
        {
          id: "S3CAI",
          key: "nasolabial_fold",
          ko: "팔자",
          en: "Nasolabial Fold",
        },
        {
          id: "S3CAN",
          key: "temple",
          ko: "관자놀이",
          en: "Temple",
        },
      ],
    },
    {
      id: "S2CB",
      key: "fat_dissolving_contouring_injection",
      ko: "지방분해/윤곽주사",
      en: "Fat Dissolving/Contouring Injection",
      children: [
        {
          id: "S3CBC",
          key: "full_face",
          ko: "풀페이스",
          en: "Full Face",
        },
        {
          id: "S3CBA",
          key: "cheek_zygomatic",
          ko: "볼/광대",
          en: "Cheek Zygomatic",
        },
        {
          id: "S3CBB",
          key: "chin",
          ko: "턱",
          en: "Chin",
        },
        {
          id: "S3CBD",
          key: "nose",
          ko: "코",
          en: "Nose",
        },
      ],
    },
  ],
},
{
  id: "S1A",
  key: "body",
  ko: "체형",
  en: "Body",
  children: [
    {
      id: "S2AD",
      key: "fat_dissolving_contouring_injection",
      ko: "지방분해/윤곽주사",
      en: "Fat Dissolving/Contouring Injection",
      children: [
        {
          id: "S3ADA",
          key: "abdomen",
          ko: "복부",
          en: "Abdomen",
        },
        {
          id: "S3ADD",
          key: "flank_love_handle",
          ko: "옆구리/러브핸들",
          en: "Flank Love Handle",
        },
        {
          id: "S3ADB",
          key: "arm",
          ko: "팔",
          en: "Arm",
        },
        {
          id: "S3ADF",
          key: "thigh",
          ko: "허벅지",
          en: "Thigh",
        },
        {
          id: "S3ADE",
          key: "knee_calf_ankle",
          ko: "무릎/종아리/발목",
          en: "Knee Calf Ankle",
        },
        {
          id: "S3ADG",
          key: "trapezius_collar_back",
          ko: "승모근/쇄골/등",
          en: "Trapezius Collar Back",
        },
        {
          id: "S3ADC",
          key: "buttock",
          ko: "엉덩이",
          en: "Buttock",
        },
        {
          id: "S3ADH",
          key: "whole_body",
          ko: "전신",
          en: "Whole Body",
        },
      ],
    },
    {
      id: "S2AC",
      key: "diet",
      ko: "다이어트",
      en: "Diet",
      children: [
        {
          id: "S3ACE",
          key: "fat_extraction_injection",
          ko: "지방추출주사",
          en: "Fat Extraction Injection",
        },
        {
          id: "S3ACA",
          key: "carboxytherapy",
          ko: "카복시테라피",
          en: "Carboxytherapy",
        },
        {
          id: "S3ACD",
          key: "diet_program",
          ko: "다이어트 프로그램",
          en: "Diet Program",
        },
        {
          id: "S3ACC",
          key: "cryolipolysis",
          ko: "냉각지방분해",
          en: "Cryolipolysis",
        },
        {
          id: "S3ACF",
          key: "laser_extracorporeal_shockwave",
          ko: "레이저/체외충격파",
          en: "Laser Extracorporeal Shockwave",
        },
        {
          id: "S3ACB",
          key: "cellulite_toning",
          ko: "셀룰라이트토닝",
          en: "Cellulite Toning",
        },
      ],
    },
    {
      id: "S2AG",
      key: "stretch_mark_treatment",
      ko: "튼살치료",
      en: "Stretch Mark Treatment",
      children: [
        {
          id: "S3AGA",
          key: "laser",
          ko: "레이저",
          en: "Laser",
        },
        {
          id: "S3AGB",
          key: "microneedle",
          ko: "마이크로니들",
          en: "Microneedle",
        },
      ],
    },
    {
      id: "S2AE",
      key: "filler",
      ko: "필러",
      en: "Filler",
      children: [
        {
          id: "S3AEB",
          key: "buttock_pelvis",
          ko: "엉덩이/골반",
          en: "Buttock Pelvis",
        },
        {
          id: "S3AEC",
          key: "calf",
          ko: "종아리",
          en: "Calf",
        },
        {
          id: "S3AEA",
          key: "breast",
          ko: "가슴",
          en: "Breast",
        },
        {
          id: "S3AED",
          key: "filler_removal",
          ko: "필러제거",
          en: "Filler Removal",
        },
      ],
    },
    {
      id: "S2AF",
      key: "lifting",
      ko: "리프팅",
      en: "Lifting",
      children: [
        {
          id: "S3AFA",
          key: "laser_lifting",
          ko: "레이저리프팅",
          en: "Laser Lifting",
        },
        {
          id: "S3AFC",
          key: "thread_lifting",
          ko: "실리프팅",
          en: "Thread Lifting",
        },
        {
          id: "S3AFB",
          key: "nerve_block_lifting",
          ko: "신경차단리프팅",
          en: "Nerve Block Lifting",
        },
      ],
    },
    {
      id: "S2AB",
      key: "botox",
      ko: "보톡스",
      en: "Botox",
      children: [
        {
          id: "S3ABD",
          key: "trapezius_collar",
          ko: "승모근/쇄골",
          en: "Trapezius Collar",
        },
        {
          id: "S3ABC",
          key: "thigh",
          ko: "허벅지",
          en: "Thigh",
        },
        {
          id: "S3ABB",
          key: "calf",
          ko: "종아리",
          en: "Calf",
        },
        {
          id: "S3ABA",
          key: "arm",
          ko: "팔",
          en: "Arm",
        },
      ],
    },
    {
      id: "S2AA",
      key: "body_whitening",
      ko: "바디미백",
      en: "Body Whitening",
      children: [
        {
          id: "S3AAA",
          key: "armpit",
          ko: "겨드랑이",
          en: "Armpit",
        },
        {
          id: "S3AAC",
          key: "elbow",
          ko: "팔꿈치",
          en: "Elbow",
        },
        {
          id: "S3AAG",
          key: "y_zone",
          ko: "Y존",
          en: "Y Zone",
        },
        {
          id: "S3AAB",
          key: "buttock",
          ko: "엉덩이",
          en: "Buttock",
        },
        {
          id: "S3AAE",
          key: "knee",
          ko: "무릎",
          en: "Knee",
        },
        {
          id: "S3AAD",
          key: "elbow_ankle",
          ko: "팔꿈치/복숭아뼈",
          en: "Elbow Ankle",
        },
        {
          id: "S3AAF",
          key: "nipple_areola",
          ko: "유두/유륜",
          en: "Nipple Areola",
        },
      ],
    },
  ],
},
{
  id: "S1E",
  key: "skin",
  ko: "피부",
  en: "Skin",
  children: [
    {
      id: "S2EB",
      key: "elasticity_regeneration",
      ko: "탄력/재생",
      en: "Elasticity Regeneration",
      children: [
        {
          id: "S3EBB",
          key: "skin_booster",
          ko: "스킨부스터",
          en: "Skin Booster",
        },
        {
          id: "S3EBA",
          key: "collagen_booster",
          ko: "콜라겐부스터",
          en: "Collagen Booster",
        },
        {
          id: "S3EBD",
          key: "vitamin_injection_iv",
          ko: "비타민주사/수액",
          en: "Vitamin Injection Iv",
        },
        {
          id: "S3EBC",
          key: "skin_care",
          ko: "스킨케어",
          en: "Skin Care",
        },
      ],
    },
    {
      id: "S2EA",
      key: "acne_pore",
      ko: "여드름/모공",
      en: "Acne/Pore",
      children: [
        {
          id: "S3EAD",
          key: "pore_care",
          ko: "모공케어",
          en: "Pore Care",
        },
        {
          id: "S3EAA",
          key: "acne_extraction",
          ko: "여드름압출",
          en: "Acne Extraction",
        },
        {
          id: "S3EAC",
          key: "acne_scar",
          ko: "여드름흉터",
          en: "Acne Scar",
        },
        {
          id: "S3EAB",
          key: "acne_inflammation",
          ko: "여드름염증",
          en: "Acne Inflammation",
        },
        {
          id: "S3EAE",
          key: "skin_care",
          ko: "스킨케어",
          en: "Skin Care",
        },
      ],
    },
    {
      id: "S2EE",
      key: "whitening_freckle_redness",
      ko: "미백/잡티/홍조",
      en: "Whitening/Freckle/Redness",
      children: [
        {
          id: "S3EEB",
          key: "melasma_freckle",
          ko: "기미/잡티/주근깨",
          en: "Melasma Freckle",
        },
        {
          id: "S3EEC",
          key: "mole_seborrheic_keratosis",
          ko: "점/검버섯",
          en: "Mole Seborrheic Keratosis",
        },
        {
          id: "S3EEF",
          key: "skin_tone_up",
          ko: "피부톤업",
          en: "Skin Tone Up",
        },
        {
          id: "S3EEA",
          key: "dark_circle",
          ko: "다크서클",
          en: "Dark Circle",
        },
        {
          id: "S3EED",
          key: "redness",
          ko: "홍조",
          en: "Redness",
        },
        {
          id: "S3EEE",
          key: "skin_care",
          ko: "스킨케어",
          en: "Skin Care",
        },
      ],
    },
    {
      id: "S2EC",
      key: "moisturizing_soothing",
      ko: "보습/진정",
      en: "Moisturizing/Soothing",
      children: [
        {
          id: "S3ECA",
          key: "skin_booster",
          ko: "스킨부스터",
          en: "Skin Booster",
        },
        {
          id: "S3ECC",
          key: "vitamin_injection_iv",
          ko: "비타민주사/수액",
          en: "Vitamin Injection Iv",
        },
        {
          id: "S3ECB",
          key: "skin_care",
          ko: "스킨케어",
          en: "Skin Care",
        },
      ],
    },
    {
      id: "S2ED",
      key: "skin_disease",
      ko: "피부질환",
      en: "Skin Disease",
      children: [
        {
          id: "S3EDA",
          key: "atopy",
          ko: "아토피",
          en: "Atopy",
        },
        {
          id: "S3EDE",
          key: "seborrheic_dermatitis",
          ko: "지루성피부염",
          en: "Seborrheic Dermatitis",
        },
        {
          id: "S3EDB",
          key: "bromhidrosis_hyperhidrosis",
          ko: "액취증/다한증",
          en: "Bromhidrosis Hyperhidrosis",
        },
        {
          id: "S3EDD",
          key: "scar_burn",
          ko: "흉터/화상",
          en: "Scar Burn",
        },
        {
          id: "S3EDG",
          key: "wart_corn",
          ko: "사마귀/티눈",
          en: "Wart Corn",
        },
        {
          id: "S3EDF",
          key: "syringoma_milia_skin_tag",
          ko: "환관종/비립종/쥐젖",
          en: "Syringoma Milia Skin Tag",
        },
        {
          id: "S3EDC",
          key: "etc",
          ko: "기타",
          en: "Etc",
        },
      ],
    },
  ],
},
{
  id: "S1D",
  key: "scalp",
  ko: "두피/탈모/제모",
  en: "Scalp",
  children: [
    {
      id: "S2DC",
      key: "scalp_hair_loss_care",
      ko: "두피/탈모케어",
      en: "Scalp Hair Loss Care",
      children: [
        {
          id: "S3DCB",
          key: "scalp_care",
          ko: "두피케어",
          en: "Scalp Care",
        },
        {
          id: "S3DCC",
          key: "scalp_hair_follicle_injection",
          ko: "두피/모낭주사",
          en: "Scalp Hair Follicle Injection",
        },
        {
          id: "S3DCA",
          key: "hair_loss_laser",
          ko: "탈모레이저",
          en: "Hair Loss Laser",
        },
      ],
    },
    {
      id: "S2DA",
      key: "hair_transplant",
      ko: "모발이식",
      en: "Hair Transplant",
      children: [
        {
          id: "S3DAA",
          key: "incision",
          ko: "절개",
          en: "Incision",
        },
        {
          id: "S3DAB",
          key: "non_incision",
          ko: "비절개",
          en: "Non Incision",
        },
      ],
    },
    {
      id: "S2DB",
      key: "laser_hair_removal",
      ko: "레이저제모",
      en: "Laser Hair Removal",
      children: [
        {
          id: "S3DBB",
          key: "face",
          ko: "얼굴",
          en: "Face",
        },
        {
          id: "S3DBA",
          key: "body",
          ko: "바디",
          en: "Body",
        },
      ],
    },
  ],
},
{
  id: "S1B",
  key: "etc",
  ko: "기타",
  en: "Etc",
  children: [
    {
      id: "S2BD",
      key: "semi_permanent_makeup",
      ko: "반영구화장",
      en: "Semi Permanent Makeup",
      children: [
        {
          id: "S3BDB",
          key: "eyebrow",
          ko: "눈썹",
          en: "Eyebrow",
        },
        {
          id: "S3BDC",
          key: "eyeliner",
          ko: "아이라인",
          en: "Eyeliner",
        },
        {
          id: "S3BDD",
          key: "lips",
          ko: "입술",
          en: "Lips",
        },
        {
          id: "S3BDF",
          key: "scalp_hairline",
          ko: "두피/헤어라인",
          en: "Scalp Hairline",
        },
        {
          id: "S3BDE",
          key: "nipple_areola",
          ko: "유두/유륜",
          en: "Nipple Areola",
        },
        {
          id: "S3BDA",
          key: "beauty_spot",
          ko: "미인점",
          en: "Beauty Spot",
        },
        {
          id: "S3BDG",
          key: "tattoo_removal",
          ko: "문신제거",
          en: "Tattoo Removal",
        },
      ],
    },
    {
      id: "S2BA",
      key: "female_procedure",
      ko: "여성시술",
      en: "Female Procedure",
    },
    {
      id: "S2BC",
      key: "post_surgery_care",
      ko: "성형후관리",
      en: "Post Surgery Care",
    },
    {
      id: "S2BB",
      key: "other_petitskin",
      ko: "기타쁘띠/피부",
      en: "Other Petitskin",
    },
  ],
},
];
