import { CategoryNode } from "./categoryNode";

  export const SKIN_BEAUTY_CATEGORIES: CategoryNode[] = [
    { key: "recommend", label: "추천", name: "Recommend" },
    {
      key: "face",
      label: "얼굴",
      name: "Face",
      children: [
        {
          key: "filler",
          label: "필러",
          name: "Filler",
          children: [
            { key: "full_face", label: "풀페이스", name: "Full Face" },
            { key: "forehead_glabella", label: "이마/미간", name: "Forehead Glabella" },
            { key: "nose", label: "코", name: "Nose" },
            { key: "lips_mouth_corner", label: "입술/입꼬리", name: "Lips Mouth Corner" },
            { key: "eyes", label: "눈", name: "Eyes" },
            { key: "chin", label: "턱", name: "Chin" },
            { key: "cheek_zygomatic", label: "볼/광대", name: "Cheek Zygomatic" },
            { key: "neck", label: "목", name: "Neck" },
            { key: "nasolabial_fold", label: "팔자", name: "Nasolabial Fold" },
            { key: "temple", label: "관자놀이", name: "Temple" },
            { key: "scalp", label: "두상", name: "Scalp" },
            { key: "filler_removal", label: "필러제거", name: "Filler Removal" },
          ],
        },
        {
          key: "lifting",
          label: "리프팅",
          name: "Lifting",
          children: [
            { key: "laser_lifting", label: "레이저리프팅", name: "Laser Lifting" },
            { key: "thread_lifting", label: "실리프팅", name: "Thread Lifting" },
            { key: "nose_lifting", label: "코리프팅", name: "Nose Lifting" },
            { key: "nerve_block_lifting", label: "신경차단리프팅", name: "Nerve Block Lifting" },
          ],
        },
        {
          key: "botox",
          label: "보톡스",
          name: "Botox",
          children: [
            { key: "full_face", label: "풀페이스", name: "Full Face" },
            { key: "chin", label: "턱", name: "Chin" },
            { key: "parotid_gland", label: "침샘", name: "Parotid Gland" },
            { key: "forehead_glabella", label: "이마/미간", name: "Forehead Glabella" },
            { key: "eyes", label: "눈", name: "Eyes" },
            { key: "skin", label: "스킨", name: "Skin" },
            { key: "lips_mouth_corner", label: "입술/입꼬리", name: "Lips Mouth Corner" },
            { key: "gums", label: "잇몸", name: "Gums" },
            { key: "hyperhidrosis", label: "다한증", name: "Hyperhidrosis" },
            { key: "cheek_zygomatic", label: "볼/광대", name: "Cheek Zygomatic" },
            { key: "nose", label: "코", name: "Nose" },
            { key: "neck", label: "목", name: "Neck" },
            { key: "nasolabial_fold", label: "팔자", name: "Nasolabial Fold" },
            { key: "temple", label: "관자놀이", name: "Temple" },
          ],
        },
        {
          key: "fat_dissolving_contouring_injection",
          label: "지방분해/윤곽주사",
          name: "Fat Dissolving/Contouring Injection",
          children: [
            { key: "full_face", label: "풀페이스", name: "Full Face" },
            { key: "cheek_zygomatic", label: "볼/광대", name: "Cheek Zygomatic" },
            { key: "chin", label: "턱", name: "Chin" },
            { key: "nose", label: "코", name: "Nose" },
          ],
        },
      ],
    },
    {
      key: "body",
      label: "체형",
      name: "Body",
      children: [
        {
          key: "fat_dissolving_contouring_injection",
          label: "지방분해/윤곽주사",
          name: "Fat Dissolving/Contouring Injection",
          children: [
            { key: "abdomen", label: "복부", name: "Abdomen" },
            { key: "flank_love_handle", label: "옆구리/러브핸들", name: "Flank Love Handle" },
            { key: "arm", label: "팔", name: "Arm" },
            { key: "thigh", label: "허벅지", name: "Thigh" },
            { key: "knee_calf_ankle", label: "무릎/종아리/발목", name: "Knee Calf Ankle" },
            { key: "trapezius_collar_back", label: "승모근/쇄골/등", name: "Trapezius Collar Back" },
            { key: "buttock", label: "엉덩이", name: "Buttock" },
            { key: "whole_body", label: "전신", name: "Whole Body" },
          ],
        },
        {
          key: "diet",
          label: "다이어트",
          name: "Diet",
          children: [
            { key: "fat_extraction_injection", label: "지방추출주사", name: "Fat Extraction Injection" },
            { key: "carboxytherapy", label: "카복시테라피", name: "Carboxytherapy" },
            { key: "diet_program", label: "다이어트 프로그램", name: "Diet Program" },
            { key: "cryolipolysis", label: "냉각지방분해", name: "Cryolipolysis" },
            { key: "laser_extracorporeal_shockwave", label: "레이저/체외충격파", name: "Laser Extracorporeal Shockwave" },
            { key: "cellulite_toning", label: "셀룰라이트토닝", name: "Cellulite Toning" },
          ],
        },
        {
          key: "stretch_mark_treatment",
          label: "튼살치료",
          name: "Stretch Mark Treatment",
          children: [
            { key: "laser", label: "레이저", name: "Laser" },
            { key: "microneedle", label: "마이크로니들", name: "Microneedle" },
          ],
        },
        {
          key: "filler",
          label: "필러",
          name: "Filler",
          children: [
            { key: "buttock_pelvis", label: "엉덩이/골반", name: "Buttock Pelvis" },
            { key: "calf", label: "종아리", name: "Calf" },
            { key: "breast", label: "가슴", name: "Breast" },
            { key: "filler_removal", label: "필러제거", name: "Filler Removal" },
          ],
        },
        {
          key: "lifting",
          label: "리프팅",
          name: "Lifting",
          children: [
            { key: "laser_lifting", label: "레이저리프팅", name: "Laser Lifting" },
            { key: "thread_lifting", label: "실리프팅", name: "Thread Lifting" },
            { key: "nerve_block_lifting", label: "신경차단리프팅", name: "Nerve Block Lifting" },
          ],
        },
        {
          key: "botox",
          label: "보톡스",
          name: "Botox",
          children: [
            { key: "trapezius_collar", label: "승모근/쇄골", name: "Trapezius Collar" },
            { key: "thigh", label: "허벅지", name: "Thigh" },
            { key: "calf", label: "종아리", name: "Calf" },
            { key: "arm", label: "팔", name: "Arm" },
          ],
        },
        {
          key: "body_whitening",
          label: "바디미백",
          name: "Body Whitening",
          children: [
            { key: "armpit", label: "겨드랑이", name: "Armpit" },
            { key: "elbow", label: "팔꿈치", name: "Elbow" },
            { key: "y_zone", label: "Y존", name: "Y Zone" },
            { key: "buttock", label: "엉덩이", name: "Buttock" },
            { key: "knee", label: "무릎", name: "Knee" },
            { key: "elbow_ankle", label: "팔꿈치/복숭아뼈", name: "Elbow Ankle" },
            { key: "nipple_areola", label: "유두/유륜", name: "Nipple Areola" },
          ],
        },
      ],
    },
    {
      key: "skin",
      label: "피부",
      name: "Skin",
      children: [
        {
          key: "elasticity_regeneration",
          label: "탄력/재생",
          name: "Elasticity Regeneration",
          children: [
            { key: "skin_booster", label: "스킨부스터", name: "Skin Booster" },
            { key: "collagen_booster", label: "콜라겐부스터", name: "Collagen Booster" },
            { key: "vitamin_injection_iv", label: "비타민주사/수액", name: "Vitamin Injection Iv" },
            { key: "skin_care", label: "스킨케어", name: "Skin Care" },
          ],
        },
        {
          key: "acne_pore",
          label: "여드름/모공",
          name: "Acne/Pore",
          children: [
            { key: "pore_care", label: "모공케어", name: "Pore Care" },
            { key: "acne_extraction", label: "여드름압출", name: "Acne Extraction" },
            { key: "acne_scar", label: "여드름흉터", name: "Acne Scar" },
            { key: "acne_inflammation", label: "여드름염증", name: "Acne Inflammation" },
            { key: "skin_care", label: "스킨케어", name: "Skin Care" },
          ],
        },
        {
          key: "whitening_freckle_redness",
          label: "미백/잡티/홍조",
          name: "Whitening/Freckle/Redness",
          children: [
            { key: "melasma_freckle", label: "기미/잡티/주근깨", name: "Melasma Freckle" },
            { key: "mole_seborrheic_keratosis", label: "점/검버섯", name: "Mole Seborrheic Keratosis" },
            { key: "skin_tone_up", label: "피부톤업", name: "Skin Tone Up" },
            { key: "dark_circle", label: "다크서클", name: "Dark Circle" },
            { key: "redness", label: "홍조", name: "Redness" },
            { key: "skin_care", label: "스킨케어", name: "Skin Care" },
          ],
        },
        {
          key: "moisturizing_soothing",
          label: "보습/진정",
          name: "Moisturizing/Soothing",
          children: [
            { key: "skin_booster", label: "스킨부스터", name: "Skin Booster" },
            { key: "vitamin_injection_iv", label: "비타민주사/수액", name: "Vitamin Injection Iv" },
            { key: "skin_care", label: "스킨케어", name: "Skin Care" },
          ],
        },
        {
          key: "skin_disease",
          label: "피부질환",
          name: "Skin Disease",
          children: [
            { key: "atopy", label: "아토피", name: "Atopy" },
            { key: "seborrheic_dermatitis", label: "지루성피부염", name: "Seborrheic Dermatitis" },
            { key: "bromhidrosis_hyperhidrosis", label: "액취증/다한증", name: "Bromhidrosis Hyperhidrosis" },
            { key: "scar_burn", label: "흉터/화상", name: "Scar Burn" },
            { key: "wart_corn", label: "사마귀/티눈", name: "Wart Corn" },
            { key: "syringoma_milia_skin_tag", label: "환관종/비립종/쥐젖", name: "Syringoma Milia Skin Tag" },
            { key: "etc", label: "기타", name: "Etc" },
          ],
        },
      ],
    },
    {
      key: "dental",
      label: "치아",
      name: "Dental",
      children: [
        { key: "orthodontics", label: "치아교정", name: "Orthodontics" },
        { key: "whitening", label: "치아미백", name: "Whitening" },
        { key: "treatment", label: "치아치료", name: "Treatment" },
        { key: "gum_care", label: "잇몸관리", name: "Gum Care" },
      ],
    },
    {
      key: "scalp",
      label: "두피/탈모/제모",
      name: "Scalp",
      children: [
        {
          key: "scalp_hair_loss_care",
          label: "두피/탈모케어",
          name: "Scalp Hair Loss Care",
          children: [
            { key: "scalp_care", label: "두피케어", name: "Scalp Care" },
            { key: "scalp_hair_follicle_injection", label: "두피/모낭주사", name: "Scalp Hair Follicle Injection" },
            { key: "hair_loss_laser", label: "탈모레이저", name: "Hair Loss Laser" },
          ],
        },
        {
          key: "hair_transplant",
          label: "모발이식",
          name: "Hair Transplant",
          children: [
            { key: "incision", label: "절개", name: "Incision" },
            { key: "non_incision", label: "비절개", name: "Non Incision" },
          ],
        },
        {
          key: "laser_hair_removal",
          label: "레이저제모",
          name: "Laser Hair Removal",
          children: [
            { key: "face", label: "얼굴", name: "Face" },
            { key: "body", label: "바디", name: "Body" },
          ],
        },
      ],
    },
    { key: "vision", label: "시력교정", name: "Vision" },
    { key: "oriental", label: "한방", name: "Oriental" },
    {
      key: "etc",
      label: "기타",
      name: "Etc",
      children: [
        {
          key: "semi_permanent_makeup",
          label: "반영구화장",
          name: "Semi Permanent Makeup",
          children: [
            { key: "eyebrow", label: "눈썹", name: "Eyebrow" },
            { key: "eyeliner", label: "아이라인", name: "Eyeliner" },
            { key: "lips", label: "입술", name: "Lips" },
            { key: "scalp_hairline", label: "두피/헤어라인", name: "Scalp Hairline" },
            { key: "nipple_areola", label: "유두/유륜", name: "Nipple Areola" },
            { key: "beauty_spot", label: "미인점", name: "Beauty Spot" },
            { key: "tattoo_removal", label: "문신제거", name: "Tattoo Removal" },
          ],
        },
        { key: "female_procedure", label: "여성시술", name: "Female Procedure" },
        { key: "post_surgery_care", label: "성형후관리", name: "Post Surgery Care" },
        { key: "other_petitskin", label: "기타쁘띠/피부", name: "Other Petitskin" },
      ],
    },
  ];
  