
export const PLASTIC_SURGERY_CATEGORIES = {
    eye: {
      label: "눈",
      double_eyelid: {
        label: "쌍꺼풀",
        natural_adhesion: "자연유착",
        buried: "매몰",
        incision: "절개",
        partial_incision: "부분벌개",
      },
      canthoplasty: {
        label: "트임",
        epicanthoplasty: "앞트임",
        lateral_canthoplasty: "뒤트임",
        upper_canthoplasty: "윗트임",
        lower_canthoplasty: "밑트임",
        mongolian_fold: "몽고트임",
        canthoplasty_revision: "트임복원",
      },
      ptosis_correction: {
        label: "눈매교정",
        incision: "절개",
        non_incision: "비절개",
      },
      eye_shape_correction: {
        label: "눈모양교정",
        lower_eyelid_fat_reposition: "눈밑지방재배치",
        upper_blepharoplasty: "상안검",
        lower_blepharoplasty: "하안검",
        brow_lift: "눈썹거상",
        lower_eyelid_fat_removal: "눈밑지방제거",
        eyelid_fat_removal: "눈꺼풀지방제거",
      },
      eye_revision: {
        label: "눈재수술",
        double_eyelid: "쌍꺼풀",
        canthoplasty: "트임",
        ptosis_correction: "눈매교정",
        eye_shape_correction: "눈모양교정",
      },
    },
    nose: {
      label: "코",
      bridge: {
        label: "콧대",
        bridge_autologous: "콧대(자가조직)",
        bridge_implant: "콧대(보형물)",
        osteotomy: "코절골술",
      },
      tip: {
        label: "코끝",
        tip_autologous: "코끝(자가조직)",
        tip_implant: "코끝(보형물)",
        tip_lengthening: "코길이연장",
      },
      ala: {
        label: "콧볼",
        non_incision: "비절개",
        medial_incision: "내측절개",
      },
      functional: {
        label: "기능코",
        rhinitis_sinusitis: "비염/축농증",
        nasal_valve_stenosis: "비밸브협착",
        septal_deviation: "비중격만곡",
      },
      nose_revision: {
        label: "코재수술",
        bridge: "콧대",
        tip: "코끝",
        ala: "콧볼",
        functional: "기능코",
      },
    },
    liposuction_fat_graft: {
      label: "지방흡입/이식",
      body_liposuction: {
        label: "바디지방흡입",
        abdomen: "복부",
        arm: "팔",
        thigh: "허벅지",
        knee_calf_ankle: "무릎/종아리/발목",
        buttock: "엉덩이",
        trapezius_collar_back: "승모근/쇄골/등",
        flank_love_handle: "옆구리/러브핸들",
        breast: "가슴",
        armpit_accessory_breast: "겨드랑이/부유방",
        whole_body: "전신",
      },
      face_liposuction: {
        label: "얼굴지방흡입",
        full_face: "풀페이스",
        forehead_glabella: "이마/미간",
        cheek_zygomatic: "볼/광대",
        chin: "턱",
        nasolabial_fold: "팔자",
      },
      face_fat_graft: {
        label: "얼굴지방이식",
        full_face: "풀페이스",
        forehead_glabella: "이마/미간",
        cheek_zygomatic: "볼/광대",
        eyes: "눈",
        chin: "턱",
        temple: "관자놀이",
        nasolabial_fold: "팔자",
        lips: "입술",
      },
      body_fat_graft: {
        label: "바디지방이식",
        breast: "가슴",
        buttock_pelvis: "엉덩이/골반",
        calf: "종아리",
      },
    },
    facial_contour_jaw: {
      label: "안면윤곽/양악",
      zygoma: {
        label: "광대",
        zygoma_implant: "광대확대(보형물)",
        zygoma_reduction: "광대축소",
      },
      contour: {
        label: "윤곽",
        square_jaw: "사각턱",
        chin: "턱끝",
        double_chin: "이중턱",
        complex_face_vline: "복합안면/V라인",
        facelift: "안면거상",
      },
      forehead: {
        label: "이마",
        forehead_implant: "이마확대(보형물)",
        forehead_reduction: "이마축소",
        forehead_lift: "이마거상",
      },
      two_jaw: {
        label: "양악",
        two_jaw: "양악",
        upper_jaw: "상악",
        lower_jaw: "하악",
      },
      contour_revision: {
        label: "안면윤곽재수술",
        zygoma: "광대",
        contour: "윤곽",
        forehead: "이마",
        two_jaw: "양악",
      },
    },
    breast: {
      label: "가슴",
      breast_shape_correction: {
        label: "가슴모양교정",
        augmentation_implant: "가슴확대(보형물)",
        mastopexy: "가슴거상",
        reduction: "가슴축소",
        implant_removal: "가슴보형물제거",
        foreign_body_removal: "가슴이물질제거",
        axillary_fat_removal: "부유방지방제거",
      },
      nipple_areola: {
        label: "유두/유륜",
        inverted_nipple: "함몰유두",
        nipple_areola_reduction: "유두/유륜축소",
      },
      breast_revision: {
        label: "가슴재수술",
        breast_shape_correction: "가슴모양교정",
        nipple_areola: "유두/유륜",
      },
    },
    male: {
      label: "남자성형",
      eye: {
        label: "눈",
        double_eyelid_or_no_eyelid: "쌍꺼풀/무쌍",
        canthoplasty: "트임",
        ptosis_correction: "눈매교정",
        eye_shape_correction: "눈모양교정",
      },
      nose: {
        label: "코",
        bridge: "콧대",
        tip: "코끝",
        ala: "콧볼",
        functional: "기능코",
      },
      breast: {
        label: "가슴",
        gynecomastia: "여유증",
        nipple_areola: "유두/유륜",
      },
      liposuction_fat_graft: {
        label: "지방흡입/이식",
        body_liposuction: "바디지방흡입",
        face_liposuction: "얼굴지방흡입",
        face_fat_graft: "얼굴지방이식",
        body_fat_graft: "바디지방이식",
      },
      facial_contour_jaw: {
        label: "안면윤곽/양악",
        zygoma: "광대",
        contour: "윤곽",
        forehead: "이마",
        two_jaw: "양악",
      },
    },
    etc: {
      label: "기타",
      female_surgery: "여성성형",
      body_lift: "바디거상",
      lip_surgery: "입술성형",
      philtrum_surgery: "인중성형",
      nasolabial_surgery: "팔자성형",
      dimple_surgery: "보조개성형",
      buttock_surgery: "엉덩이성형",
      ear_surgery: "귀성형",
      other_surgery: "기타성형",
    },
  };
  