export const SKIN_BEAUTY_CATEGORIES = {
    face: {
      label: "얼굴",
      filler: {
        label: "필러",
        full_face: "풀페이스",
        forehead_glabella: "이마/미간",
        nose: "코",
        lips_mouth_corner: "입술/입꼬리",
        eyes: "눈",
        chin: "턱",
        cheek_zygomatic: "볼/광대",
        neck: "목",
        nasolabial_fold: "팔자",
        temple: "관자놀이",
        scalp: "두상",
        filler_removal: "필러제거",
      },
      lifting: {
        label: "리프팅",
        laser_lifting: "레이저리프팅",
        thread_lifting: "실리프팅",
        nose_lifting: "코리프팅",
        nerve_block_lifting: "신경차단리프팅",
      },
      botox: {
        label: "보톡스",
        full_face: "풀페이스",
        chin: "턱",
        parotid_gland: "침샘",
        forehead_glabella: "이마/미간",
        eyes: "눈",
        skin: "스킨",
        lips_mouth_corner: "입술/입꼬리",
        gums: "잇몸",
        hyperhidrosis: "다한증",
        cheek_zygomatic: "볼/광대",
        nose: "코",
        neck: "목",
        nasolabial_fold: "팔자",
        temple: "관자놀이",
      },
      fat_dissolving_contouring_injection: {
        label: "지방분해/윤곽주사",
        full_face: "풀페이스",
        cheek_zygomatic: "볼/광대",
        chin: "턱",
        nose: "코",
      },
    },
    body: {
      label: "체형",
      fat_dissolving_contouring_injection: {
        label: "지방분해/윤곽주사",
        abdomen: "복부",
        flank_love_handle: "옆구리/러브핸들",
        arm: "팔",
        thigh: "허벅지",
        knee_calf_ankle: "무릎/종아리/발목",
        trapezius_collar_back: "승모근/쇄골/등",
        buttock: "엉덩이",
        whole_body: "전신",
      },
      diet: {
        label: "다이어트",
        fat_extraction_injection: "지방추출주사",
        carboxytherapy: "카복시테라피",
        diet_program: "다이어트 프로그램",
        cryolipolysis: "냉각지방분해",
        laser_extracorporeal_shockwave: "레이저/체외충격파",
        cellulite_toning: "셀룰라이트토닝",
      },
      stretch_mark_treatment: {
        label: "튼살치료",
        laser: "레이저",
        microneedle: "마이크로니들",
      },
      filler: {
        label: "필러",
        buttock_pelvis: "엉덩이/골반",
        calf: "종아리",
        breast: "가슴",
        filler_removal: "필러제거",
      },
      lifting: {
        label: "리프팅",
        laser_lifting: "레이저리프팅",
        thread_lifting: "실리프팅",
        nerve_block_lifting: "신경차단리프팅",
      },
      botox: {
        label: "보톡스",
        trapezius_collar: "승모근/쇄골",
        thigh: "허벅지",
        calf: "종아리",
        arm: "팔",
      },
      body_whitening: {
        label: "바디미백",
        armpit: "겨드랑이",
        elbow: "팔꿈치",
        y_zone: "Y존",
        buttock: "엉덩이",
        knee: "무릎",
        elbow_ankle: "팔꿈치/복숭아뼈",
        nipple_areola: "유두/유륜",
      },
    },
    skin: {
      label: "피부",
      elasticity_regeneration: {
        label: "탄력/재생",
        skin_booster: "스킨부스터",
        collagen_booster: "콜라겐부스터",
        vitamin_injection_iv: "비타민주사/수액",
        skin_care: "스킨케어",
      },
      acne_pore: {
        label: "여드름/모공",
        pore_care: "모공케어",
        acne_extraction: "여드름압출",
        acne_scar: "여드름흉터",
        acne_inflammation: "여드름염증",
        skin_care: "스킨케어",
      },
      whitening_freckle_redness: {
        label: "미백/잡티/홍조",
        melasma_freckle: "기미/잡티/주근깨",
        mole_seborrheic_keratosis: "점/검버섯",
        skin_tone_up: "피부톤업",
        dark_circle: "다크서클",
        redness: "홍조",
        skin_care: "스킨케어",
      },
      moisturizing_soothing: {
        label: "보습/진정",
        skin_booster: "스킨부스터",
        vitamin_injection_iv: "비타민주사/수액",
        skin_care: "스킨케어",
      },
      skin_disease: {
        label: "피부질환",
        atopy: "아토피",
        seborrheic_dermatitis: "지루성피부염",
        bromhidrosis_hyperhidrosis: "액취증/다한증",
        scar_burn: "흉터/화상",
        wart_corn: "사마귀/티눈",
        syringoma_milia_skin_tag: "환관종/비립종/쥐젖",
        etc: "기타",
      }
    },
    dental: {
      label: "치아",
      orthodontics: "치아교정",
      whitening: "치아미백",
      treatment: "치아치료",
      gum_care: "잇몸관리",
    },
    scalp_hair_removal: {
      label: "두피/탈모/제모",
      scalp_hair_loss_care: {
        label: "두피/탈모케어",
        scalp_care: "두피케어",
        scalp_hair_follicle_injection: "두피/모낭주사",
        hair_loss_laser: "탈모레이저",
      },
      hair_transplant: {
        label: "모발이식",
        incision: "절개",
        non_incision: "비절개",
      },
      laser_hair_removal: {
        label: "레이저제모",
        face: "얼굴",
        body: "바디",
      }
    },
    vision_correction: {
      label: "시력교정",
    },
    oriental_medicine: {
      label: "한방",
    },
    etc: {
      label: "기타",
      semi_permanent_makeup: {
        label: "반영구화장",
        eyebrow: "눈썹",
        eyeliner: "아이라인",
        lips: "입술",
        scalp_hairline: "두피/헤어라인",
        nipple_areola: "유두/유륜",
        beauty_spot: "미인점",
        tattoo_removal: "문신제거",
      },
      female_procedure: "여성시술",
      post_surgery_care: "성형후관리",
      other_petitskin: "기타쁘띠/피부",
    },
  };
  